# Generated by Django 3.0.7 on 2020-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Гарчиг')),
                ('value', models.TextField(verbose_name='Товч агуулга')),
                ('agency_name', models.CharField(max_length=250, verbose_name='Агентлагийн нэр')),
                ('agency_contact_address', models.CharField(max_length=250, verbose_name='Хаяг')),
                ('agency_contact_phone', models.PositiveIntegerField(verbose_name='Утас')),
                ('agency_contact_email', models.CharField(max_length=250, verbose_name='Е-Мэйл')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Агентлагийн мэдээлэл',
            },
        ),
    ]
