# Generated by Django 3.0.7 on 2020-07-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='footer_text',
            field=models.CharField(default=1, max_length=250, verbose_name='Сайтын хөл текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='agency_name',
            field=models.CharField(max_length=250, verbose_name='Байгууллагын нэр'),
        ),
    ]
