# Generated by Django 3.0.7 on 2020-07-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0002_auto_20200709_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='agency_contact_address',
        ),
        migrations.RemoveField(
            model_name='config',
            name='agency_contact_email',
        ),
        migrations.RemoveField(
            model_name='config',
            name='agency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='config',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='footer_text',
        ),
    ]
