# Generated by Django 3.0.6 on 2020-07-14 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0003_auto_20200709_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='config',
            table='config',
        ),
    ]
