# Generated by Django 3.0.6 on 2020-07-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0005_auto_20200714_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ('id',), 'verbose_name_plural': 'Агентлагийн мэдээлэл'},
        ),
    ]
