# Generated by Django 3.0.7 on 2020-11-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0006_auto_20200714_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=50)),
                ('request_data', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
