# Generated by Django 3.0.7 on 2020-11-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0007_error500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='error500',
            table='error500',
        ),
    ]
