# Generated by Django 3.0.7 on 2020-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0008_auto_20201106_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error500',
            name='request_data',
        ),
        migrations.AddField(
            model_name='error500',
            name='request_headers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='error500',
            name='request_scheme',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='error500',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='error500',
            name='request_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='error500',
            name='request_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
