# Generated by Django 3.0.7 on 2020-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0009_auto_20201109_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='error500',
            name='request_data',
            field=models.TextField(null=True),
        ),
    ]
