# Generated by Django 3.0.7 on 2021-02-23 04:19

from django.db import migrations


def _has_value(Model, object):
    has_value = False
    config_qs = Model.objects
    config_qs = config_qs.filter(name=object['name'], value__isnull=False)
    if config_qs:
        has_value = True

    return has_value


def create_erguul_ungu_config(apps, schema_editor):

    Config = apps.get_model('backend_config', 'Config')

    obj = dict()
    obj['name'] = 'erguul_ungu'
    obj['value'] = '#0faf04'

    has_value = _has_value(Config, obj)
    if not has_value:
        Config.objects.create(**obj)


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0010_error500_request_data'),
    ]

    operations = [
        migrations.RunPython(create_erguul_ungu_config),
    ]
