# Generated by Django 3.0.7 on 2021-03-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0024_employee_pro_class'),
        ('backend_config', '0011_auto_20210223_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Гарчиг')),
                ('value', models.TextField(verbose_name='Товч агуулга')),
                ('mn_name', models.CharField(db_index=True, max_length=250, null=True, verbose_name='Монгол нэр')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org', verbose_name='Байгууллага')),
            ],
            options={
                'db_table': 'config_covid',
                'ordering': ('id',),
            },
        ),
    ]
