# Generated by Django 3.0.7 on 2021-03-17 02:13

from django.db import migrations


def _move_datas(apps, schema):
    Config = apps.get_model('backend_config', 'Config')
    CovidConfig = apps.get_model('backend_config', 'CovidConfig')

    default_values = {
        'emy_logo': '',
        'batlagdsan_tohioldol': '',
        'edgersen_humuusiin_too': '',
        'emchlegdej_bui_humuus_too': '',
        'tusgaarlagdsan_humuusiin_too': '',
        'medeellin_eh_survalj': '',
        'emiin_sangiin_too': '',
        'emlegiin_too': '',
        'niit_eruul_mend_baiguullaga_too': '',
        'gzbgzzg_logo': '',
        'title': '',
        'bundle': '',
        'shinjilgee_too': '',
        'nas_barsan_too': '',
        'erguul_ungu': '',
        'line_chart_datas': '',
    }

    configs = Config.objects.filter(name__in=default_values.keys())
    for config in configs:
        data = dict()
        data['name'] = config.name
        data['value'] = config.value
        CovidConfig.objects.create(**data)
        config.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0012_covidconfig'),
    ]

    operations = [
        migrations.RunPython(_move_datas),
    ]
