# Generated by Django 3.0.7 on 2021-03-17 02:13

from django.db import migrations


def _move_datas(apps, schema):
    Config = apps.get_model('backend_config', 'Config')
    CovidConfig = apps.get_model('backend_config', 'CovidConfig')

    default_values = {
        'emy_logo': 'Эрүүл мэндийн яамны лого',
        'batlagdsan_tohioldol': 'Батлагдсан тохиолдол',
        'edgersen_humuusiin_too': 'Эдгэрсэн хүмүүсийн тоо',
        'emchlegdej_bui_humuus_too': 'Эмчлэгдэж буй хүмүүсийн тоо',
        'tusgaarlagdsan_humuusiin_too': 'Тусгаарлагдаж буй хүмүүсийн тоо',
        'medeellin_eh_survalj': 'Мэдээллийн эх сурвалж',
        'emiin_sangiin_too': 'Эмийн сангийн тоо',
        'emlegiin_too': 'Эмнэлэгийн тоо',
        'niit_eruul_mend_baiguullaga_too': 'Нийт эрүүл мэндийн байгууллагын тоо',
        'gzbgzzg_logo': 'ГЗБГЗЗГ лого',
        'title': 'Гарчиг',
        'bundle': 'Дэд сан',
        'shinjilgee_too': 'Шинжилгээ хийсэн тоо',
        'nas_barsan_too': 'Нас барсан хүмүүсийн тоо',
        'erguul_ungu': 'Эргүүлд гарч буй хүний өнгө',
        'line_chart_datas': 'Line Chart',
    }

    configs = Config.objects.filter(name__in=default_values.keys())
    for config in configs:
        data = dict()
        data['name'] = config.name
        data['value'] = config.value
        data['mn_name'] = default_values[config.name]
        CovidConfig.objects.create(**data)
        config.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0012_covidconfig'),
    ]

    operations = [
        migrations.RunPython(_move_datas),
    ]
