# Generated by Django 3.0.7 on 2021-03-26 06:15

from django.db import migrations


def create_payment_config(apps, schema_editor):

    Config = apps.get_model('backend_config', 'Config')

    datas = (
        ('POLYGON_PER_KM_AMOUNT', '1'),
        ('POLYGON_PER_M_AMOUNT', '1000'),
        ('PROPERTY_PER_AMOUNT', '1'),
    )

    for key, value in datas:
        conf = Config.objects.filter(name=key)
        if not conf:
            conf.create(
                name=key,
                value=value
            )


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0014_auto_20210312_1725'),
    ]

    operations = [
          migrations.RunPython(create_payment_config)
    ]
