# Generated by Django 3.0.7 on 2021-03-26 06:15

from django.db import migrations

def _check_value(Model, values):
    check_value = False
    config_qs = Model.objects
    for name, value in values:
        config_qs = config_qs.filter(name=name, value__isnull=False)
    if config_qs:
        check_value = True

    return check_value


def MigTest(apps,schema_editor):

    Config = apps.get_model('backend_config', 'Config')

    datas = (
        ('POLYGON_PER_KM_AMOUNT', '1'),
        ('POLYGON_PER_M_AMOUNT', '1000'),
        ('PROPERTY_PER_AMOUNT', '1'),
    )

    check_value = _check_value(Config, datas)
    if not check_value:
        for name, value in datas:
            Config.objects.create(name=name, value=value)


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0014_auto_20210312_1725'),
    ]

    operations = [
        migrations.RunPython(MigTest)
    ]


