# Generated by Django 3.0.7 on 2021-03-29 03:08

from django.db import migrations


def create_qpay_config(apps, schema_editor):

    Config = apps.get_model('backend_config', 'Config')

    values = (
        ('id', 'CUST_001'),
        ('register_no', 'ddf'),
        ('name', 'Central brnach'),
        ('email', 'info@info.mn'),
        ('phone_number', '99888899'),
        ('note', 'davaa')
    )

    for key, value in values:
        config = Config.objects.filter(name=key, value=value)
        if not config:
            config.create(
                name=key,
                value=value
            )


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0015_auto_20210326_1536'),
    ]

    operations = [
        migrations.RunPython(create_qpay_config),
    ]
