# Generated by Django 3.0.5 on 2021-04-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0016_auto_20210329_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidConfig',
        ),
    ]
