# Generated by Django 3.0.7 on 2021-07-09 07:45

from django.db import migrations

def create_point_config(apps, schema):
    Config = apps.get_model('backend_config', 'Config')
    point_config = Config.objects.filter(name='point_price').first()
    if not point_config:
        Config.objects.create(name='point_price')

class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0017_delete_covidconfig'),
    ]

    operations = [
         migrations.RunPython(create_point_config),
    ]
