# Generated by Django 3.0.7 on 2021-07-09 07:45

from django.db import migrations
from main.utils import json_dumps


def create_point_config(apps, schema):
    Config = apps.get_model('backend_config', 'Config')
    point_config = Config.objects.filter(name='POINT_PRICE').first()
    value = {
        'G101_P': 5600,
        'G102_P': 5600,
        'G103_P': 5600,
        'G104_P': 5600,
        'G105_P': 5600,
        'G106_P': 5600,
        'G107_P': 5600,
    }
    value = json_dumps(value)
    if not point_config:
        Config.objects.create(name='POINT_PRICE', value=value)


class Migration(migrations.Migration):

    dependencies = [
        ('backend_config', '0017_delete_covidconfig'),
    ]

    operations = [
         migrations.RunPython(create_point_config),
    ]
