# Generated by Django 3.0.6 on 2020-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0002_auto_20200530_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'role1'), (2, 'role2'), (3, 'role3'), (4, 'role4'), (5, 'admin')], primary_key=True, serialize=False),
        ),
    ]
