# Generated by Django 3.0.6 on 2020-05-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0003_auto_20200530_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Цэс', 'verbose_name_plural': 'Цэсүүд'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Хэрэглэгчийн эрх', 'verbose_name_plural': 'Хэрэглэгчийн эрхүүд'},
        ),
    ]
