# Generated by Django 3.0.6 on 2020-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0004_auto_20200530_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='register',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
