# Generated by Django 3.0.6 on 2020-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0005_auto_20200613_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
