# Generated by Django 3.0.7 on 2020-11-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0011_password_hash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'role1'), (2, 'role2'), (5, 'admin')], primary_key=True, serialize=False),
        ),
    ]
