# Generated by Django 3.0.7 on 2020-11-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0012_auto_delete_11_04'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
