# Generated by Django 3.0.7 on 2020-11-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0013_user_is_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
