# Generated by Django 3.0.7 on 2020-11-18 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0015_auto_20201118_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.CreateModel(
            name='UserValidationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False)),
                ('token', models.CharField(db_index=True, max_length=100, null=True)),
                ('valid_before', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
