# Generated by Django 3.0.6 on 2020-07-08 10:33

from django.db import migrations, models
from django.core import serializers

def remove_users(apps, schema_editor):

    User = apps.get_model('geoportal_app', 'User')
    users = User.objects.filter(
                is_sso=False,
                gender__isnull=True,
                register__isnull=True,
                is_active=False,
                last_login__isnull=True,
                is_superuser=False
            )
    users.delete()




class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0016_auto_20201118_0858'),
    ]

    operations = [
        migrations.RunPython(remove_users),
    ]
