# Generated by Django 3.0.7 on 2021-03-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0018_user_davhtsal_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
