# Generated by Django 3.0.7 on 2021-07-05 11:54

from django.db import migrations, models
import geoportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0019_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.CharField(error_messages={'invalid_register': 'Буруу регистр оруулсан байна!'}, max_length=10, null=True, validators=[geoportal_app.models.UserRegistratioinNumberValidator()]),
        ),
    ]
