# Generated by Django 3.0.7 on 2021-07-28 06:31

from django.db import migrations, models
import geoportal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0020_auto_20210705_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.CharField(max_length=10, null=True, validators=[geoportal_app.models.UserRegistratioinNumberValidator()]),
        ),
    ]
