# Generated by Django 3.0.7 on 2020-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Мэйл хаягаа баталгаажуулах'), (2, 'Нууц үг сэргээх'), (3, 'WMS, WFS, WMTS-руу албан хаагч хандах'), (4, 'WMS, WFS, WMTS-руу байгууллагын системээс хандах')])),
                ('token', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('kind', 'token')},
            },
        ),
    ]
