# Generated by Django 3.0.7 on 2021-04-07 10:03

from django.db import migrations
from main import utils


def _create_mssql_config(apps, schema):
    Config = apps.get_model('backend_config', 'Config')

    name = 'MSSQL_CONNECTION'

    value = {
        'msssql_server': '',
        'msssql_port': '1433',
        'msssql_username': '',
        'msssql_password': '',
        'msssql_database': '',
    }

    value = utils.json_dumps(value)

    config_qs = Config.objects
    config_qs = config_qs.create(
        name=name,
        value=value,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(_create_mssql_config),
    ]
