# Generated by Django 3.0.7 on 2020-11-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govorg_backend_meta_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='summary',
            new_name='abstract',
        ),
    ]
