# Generated by Django 3.0.7 on 2020-12-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govorg_backend_meta_data', '0002_auto_20201111_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='org_name',
            field=models.CharField(max_length=50, verbose_name='Бэлдсэн байгууллага'),
        ),
    ]
