# Generated by Django 3.0.5 on 2021-04-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_another_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabase',
            name='db_type',
            field=models.PositiveIntegerField(choices=[(1, 'MSSQL'), (2, 'MONGODB')], db_index=True, null=True, verbose_name='Төлөв'),
        ),
    ]
