# Generated by Django 3.0.5 on 2021-04-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_another_database', '0002_anotherdatabase_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabase',
            name='crontab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anotherdatabase',
            name='crontab_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
