# Generated by Django 3.0.7 on 2021-06-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_another_database', '0004_auto_20210426_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotherdatabasetable',
            name='field_config_index',
            field=models.TextField(null=True),
        ),
    ]
