# Generated by Django 3.0.7 on 2021-07-01 06:23
from backend.another_database.models import AnotherDatabase
from django.apps import apps
from django.db import migrations

def set_unique_id_to_tables(apps, schema_editor):
    ano_db = apps.get_model('backend_another_database', 'AnotherDatabase')
    ano_db_table = apps.get_model('backend_another_database', 'AnotherDatabaseTable')
    another_db = ano_db.objects.filter(is_export=False)
    for ano_table in another_db:
        unique_id = -1
        tables = ano_db_table.objects.filter(another_database=ano_table)
        for table in tables:
            table.table_unique_id = unique_id
            table.save()
            unique_id += -1


class Migration(migrations.Migration):

    dependencies = [
        ('backend_another_database', '0007_anotherdatabasetable_table_unique_id'),
    ]

    operations = [
        migrations.RunPython(set_unique_id_to_tables)
    ]
