# Generated by Django 3.0.7 on 2020-11-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0003_auto_20201113_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empperminspire',
            name='emp_role_inspire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_inspire.EmpRoleInspire'),
        ),
        migrations.AlterField(
            model_name='empperminspire',
            name='gov_perm_inspire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_inspire.GovPermInspire'),
        ),
        migrations.AlterField(
            model_name='emproleinspire',
            name='gov_perm_inspire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_inspire.GovPermInspire'),
        ),
        migrations.AlterField(
            model_name='govperminspire',
            name='gov_role_inspire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_inspire.GovRoleInspire'),
        ),
    ]
