# Generated by Django 3.0.7 on 2020-11-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0006_auto_20201115_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govperm',
            name='geo_id',
        ),
    ]
