# Generated by Django 3.0.7 on 2021-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0008_auto_20201214_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDatas',
            fields=[
                ('transport_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geo_id', models.CharField(max_length=100, null=True)),
                ('feature_config_id', models.IntegerField(null=True)),
                ('data_type_id', models.IntegerField(null=True)),
                ('property_id', models.IntegerField(null=True)),
                ('code_list_id', models.IntegerField(null=True)),
                ('value_text', models.CharField(max_length=4000, null=True)),
                ('value_number', models.FloatField(null=True)),
                ('value_date', models.DateTimeField(null=True)),
                ('value_connected_geo_id', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('modified_on', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'm_datas',
                'managed': False,
            },
        ),
    ]
