# Generated by Django 3.0.7 on 2021-07-28 02:01

from django.db import migrations, models
from django.db.migrations.operations.special import RunPython
import django.db.models.deletion
from django.contrib.sessions.backends.db import SessionStore
from django.core.cache import cache


CACHE_KEY = 'gov_role_inspire_datas'


def _saveDatas(apps, schema):
    GovRoleInspire = apps.get_model('backend_inspire', 'GovRoleInspire')
    datas = list(GovRoleInspire.objects.values('id', 'data_type_id', 'feature_id', 'property_id'))

    cache.set(CACHE_KEY, datas, 300)

    print("\n")
    print('\x1b[6;30;42m' + '...Датаг хадгалж авлаа...' + '\x1b[0m')


def _insertDatas(apps, schema):
    GovRoleInspire = apps.get_model('backend_inspire', 'GovRoleInspire')

    print('\33[94m' + "Датаг оруулж эхэллээ" + '\33[0m')

    datas = cache.get(CACHE_KEY)
    for role_perm in datas:
        qs = GovRoleInspire.objects
        qs = qs.filter(id=role_perm['id'])

        del role_perm['id']

        qs.update(**role_perm)

    print('\x1b[6;30;42m' + 'Уншиж дууслаа' + '\x1b[0m')


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0012_auto_20210121_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MDatasBoundary',
        ),
        migrations.DeleteModel(
            name='MDatasBuilding',
        ),
        migrations.DeleteModel(
            name='MDatasCadastral',
        ),
        migrations.DeleteModel(
            name='MDatasGeographical',
        ),
        migrations.DeleteModel(
            name='MDatasHydrography',
        ),
        migrations.RunPython(_saveDatas),
        migrations.RemoveField(
            model_name='govroleinspire',
            name='data_type_id',
        ),
        migrations.RemoveField(
            model_name='govroleinspire',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='govroleinspire',
            name='property_id',
        ),
        migrations.AddField(
            model_name='govroleinspire',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LDataTypes'),
        ),
        migrations.AddField(
            model_name='govroleinspire',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LFeatures'),
        ),
        migrations.AddField(
            model_name='govroleinspire',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LProperties'),
        ),
        migrations.RunPython(_insertDatas),
    ]
