# Generated by Django 3.0.7 on 2021-02-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WmtsCacheConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('img_format', models.CharField(max_length=50)),
                ('zoom_start', models.IntegerField(null=True)),
                ('zoom_stop', models.IntegerField()),
                ('type_of_operation', models.CharField(max_length=255)),
                ('number_of_tasks_to_use', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geoserver_wmts_cache_config',
                'ordering': ('created_at',),
            },
        ),
    ]
