# Generated by Django 3.0.7 on 2021-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmtscacheconfig',
            name='group_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wmtscacheconfig',
            name='feature_id',
            field=models.IntegerField(null=True),
        ),
    ]
