# Generated by Django 3.0.7 on 2021-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0002_auto_20210303_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmtscacheconfig',
            name='feature_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
