# Generated by Django 3.0.7 on 2021-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0006_replace_design_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmtscacheconfig',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
