# Generated by Django 3.0.7 on 2021-06-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0007_wmtscacheconfig_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmtscacheconfig',
            name='img_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wmtscacheconfig',
            name='number_of_tasks_to_use',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wmtscacheconfig',
            name='type_of_operation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wmtscacheconfig',
            name='zoom_stop',
            field=models.IntegerField(null=True),
        ),
    ]
