# Generated by Django 3.0.7 on 2021-06-16 04:08

from django.db import migrations

def get_feature_count_from_mgeo(apps, schema_editor):
    wmts_configs = apps.get_model('backend_geoserver', 'WmtsCacheConfig')
    m_geo_datas = apps.get_model('backend_inspire', 'MGeoDatas')
    for wmts_config in wmts_configs .objects.all():
        feature = m_geo_datas.objects.filter(feature_id=wmts_config.feature_id)
        wmts_config.feature_count = feature.count()
        wmts_config.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0007_wmtscacheconfig_is_modified'),
    ]

    operations = [
         migrations.RunPython(get_feature_count_from_mgeo),
    ]
