# Generated by Django 3.0.7 on 2021-07-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_geoserver', '0008_auto_20210630_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmtscacheconfig',
            name='feature_count',
        ),
    ]
