# Generated by Django 3.0.7 on 2020-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
