# Generated by Django 3.0.6 on 2020-07-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0003_auto_20200705_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmslayer',
            options={'ordering': ('sort_order',)},
        ),
    ]
