# Generated by Django 3.0.7 on 2020-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0004_auto_20200705_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='LegendURL',
            field=models.CharField(default='null', max_length=999),
            preserve_default=False,
        ),
    ]
