# Generated by Django 3.0.6 on 2020-07-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0005_wmslayer_legendurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wmslayer',
            old_name='LegendURL',
            new_name='legend_url',
        ),
    ]
