# Generated by Django 3.0.7 on 2020-09-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0006_auto_20200723_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='feature_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='geodb_export_field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='geodb_pk_field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='geodb_schema',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wmslayer',
            name='geodb_table',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
