# Generated by Django 3.0.7 on 2020-09-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0007_auto_20200913_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='feature_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
