# Generated by Django 3.0.7 on 2020-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0008_auto_20200917_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmslayer',
            name='legend_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
