# Generated by Django 3.0.7 on 2020-12-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0009_auto_20201102_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslayer',
            name='legend_url',
        ),
    ]
