# Generated by Django 3.0.7 on 2020-08-01 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_bundle', '0007_auto_20200623_1517'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.PositiveIntegerField(choices=[(1, '1-р түвшин'), (2, '2-р түвшин'), (3, '3-р түвшин')], db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_view', models.BooleanField(db_index=True)),
                ('perm_create', models.BooleanField(db_index=True)),
                ('perm_remove', models.BooleanField(db_index=True)),
                ('perm_revoke', models.BooleanField(db_index=True)),
                ('perm_review', models.BooleanField(db_index=True)),
                ('perm_approve', models.BooleanField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_bundle.Bundle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org')),
            ],
            options={
                'unique_together': {('org', 'bundle')},
            },
        ),
    ]
