# Generated by Django 3.0.7 on 2020-08-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, '1-р түвшин'), (2, '2-р түвшин'), (3, '3-р түвшин'), (4, '4-р түвшин')], db_index=True),
        ),
    ]
