# Generated by Django 3.0.7 on 2020-10-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0003_orginspireroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginspireroles',
            name='module_root_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
