# Generated by Django 3.0.7 on 2020-11-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0006_auto_20201026_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgInspireRoles',
            new_name='InspirePerm',
        ),
    ]
