# Generated by Django 3.0.7 on 2020-12-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0011_perm_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='token',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
