# Generated by Django 3.0.7 on 2020-12-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0012_employee_toke'),
        ('backend_org', '0011_perm_create'),
    ]

    operations = [
    ]
