# Generated by Django 3.0.7 on 2021-01-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0015_multilinestring_to_multipolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspirePerm',
        ),
    ]
