# Generated by Django 3.0.7 on 2021-02-16 05:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0016_delete_inspireperm'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(max_length=250, null=True)),
                ('level_2', models.CharField(max_length=250, null=True)),
                ('level_3', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_org.Employee')),
            ],
        ),
    ]
