# Generated by Django 3.0.7 on 2021-02-17 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0017_auto_20210216_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeErguul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_3', models.CharField(max_length=100, null=True, verbose_name='Баг/Хороо')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Гудамж')),
                ('apartment', models.CharField(max_length=100, null=True, verbose_name='Байр')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Байршил')),
                ('part_time', models.PositiveIntegerField(choices=[(1, 'Үдээс хойш'), (2, 'Үдээс өмнө')], db_index=True, verbose_name='Ээлж')),
                ('date_start', models.DateTimeField(verbose_name='Эхлэх огноо')),
                ('date_end', models.DateTimeField(verbose_name='Дуусах огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Оноосон огноо')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_org.EmployeeAddress', verbose_name='Ажилтан')),
            ],
        ),
        migrations.CreateModel(
            name='ErguulTailbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveIntegerField(choices=[(1, 'Гарсан'), (2, 'Гараагүй')], db_index=True, verbose_name='Төлөв')),
                ('description', models.CharField(db_index=True, max_length=10000, verbose_name='Тайлбар')),
                ('erguul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_org.EmployeeErguul')),
            ],
        ),
    ]
