# Generated by Django 3.0.7 on 2021-03-03 07:53

from django.db import migrations


def _check_tailbar_duplicate(apps, schema_editor):
    ErguulTailbar = apps.get_model('backend_org', 'ErguulTailbar')
    tailbar_qs = ErguulTailbar.objects.all()
    for tailbar in tailbar_qs:
        qs = ErguulTailbar.objects
        qs = qs.filter(id=tailbar.id)
        if len(qs) > 1:
            first_tailbar = qs.first()
            exclude_first = qs.exclude(id=first_tailbar.id)
            for delete_tailbar in exclude_first:
                delete_tailbar.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0018_employeeerguul_erguultailbar'),
    ]

    operations = [
        migrations.RunPython(_check_tailbar_duplicate),
    ]
