# Generated by Django 3.0.7 on 2021-02-24 03:37

from django.db import migrations, models
import django.db.models.deletion


def _check_tailbar_duplicate(apps, schema_editor):
    ErguulTailbar = apps.get_model('backend_org', 'ErguulTailbar')
    tailbar_qs = ErguulTailbar.objects.all()
    for tailbar in tailbar_qs:
        qs = ErguulTailbar.objects
        qs = qs.filter(id=tailbar.id)
        if len(qs) > 1:
            first_tailbar = qs.first()
            exclude_first = qs.exclude(id=first_tailbar.id)
            for delete_tailbar in exclude_first:
                delete_tailbar.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0018_employeeerguul_erguultailbar'),
    ]

    operations = [
        migrations.RunPython(_check_tailbar_duplicate),

        migrations.AddField(
            model_name='employeeerguul',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erguultailbar',
            name='erguul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_org.EmployeeErguul'),
        ),
    ]
