# Generated by Django 3.0.7 on 2021-02-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0018_employeeerguul_erguultailbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeerguul',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
