# Generated by Django 3.0.7 on 2021-02-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0019_employeeerguul_is_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erguultailbar',
            name='erguul',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_org.EmployeeErguul'),
        ),
    ]
