# Generated by Django 3.0.7 on 2021-03-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0020_auto_20210224_1138'),
    ]

    def _delete_position_datas(apps, schema_editor):
        Employee = apps.get_model('backend_org', 'Employee')
        Employee.objects.update(position=1)


    def _insert_datas(apps, schema_editor):
        DefaultPosition = apps.get_model('backend_org', 'DefaultPosition')
        item_list = [
            'Байхгүй', 'Сайд', 'Дэд сайд', 'Төрийн нарийн бичгийн дарга',
            'Дарга', 'Орлогч дарга', 'Тэргүүн дэд',
            'Газрын дарга', 'Хэлтсийн дарга', 'Ахлах шинжээч',
            'Шинжээч', 'Ахлах мэргэжилтэн', 'Мэргэжилтэн',
            'Зөвлөх'
        ]

        for item in item_list:
            DefaultPosition.objects.create(
                name=item
            )


    operations = [
        migrations.CreateModel(
            name='DefaultPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Албан тушаалын нэр')),
            ],
            options={
                'db_table': 'backend_org_default_positions',
            },
        ),
        migrations.RunPython(_insert_datas),

        migrations.RunPython(_delete_position_datas),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.DefaultPosition'),
        ),
    ]
