# Generated by Django 3.0.7 on 2021-03-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0021_auto_20210310_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'Ажиллаж байгаа'), (2, 'Чөлөөтэй'), (3, 'Чөлөөлөгдсөн'), (4, 'Өвчтэй')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
