# Generated by Django 3.0.7 on 2021-03-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0007_make_id_index'),
        ('backend_org', '0021_auto_20210224_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NemaWMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('is_open', models.PositiveIntegerField(choices=[(1, 'Нээлттэй'), (2, 'Хаалттай')], db_index=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_wms.WMS')),
            ],
        ),
    ]
