# Generated by Django 3.0.7 on 2021-03-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0022_nemawms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nemawms',
            name='wms',
        ),
    ]
