# Generated by Django 3.0.7 on 2021-03-15 03:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0022_employee_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaddress',
            name='address_state',
            field=models.PositiveIntegerField(choices=[(1, 'Байнгын оршин суугаа хаяг'), (2, 'Түр оршин суугаа хаяг')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
