# Generated by Django 3.0.7 on 2021-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0023_employeeaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pro_class',
            field=models.PositiveIntegerField(choices=[(1, 'Ангийн дарга'), (2, 'Гишүүн'), (3, 'Нарийн бичгийн дарга')], null=True),
        ),
    ]
