# Generated by Django 3.0.5 on 2021-04-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0025_nemawms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NemaWMS',
        ),
    ]
