# Generated by Django 3.0.7 on 2021-06-16 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0026_delete_nemawms'),
    ]

    operations = [
        migrations.AddField(
            model_name='Position',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org'),
        ),
        migrations.AlterModelTable(
            name='Position',
            table='backend_org_position',
        ),
    ]
