# Generated by Django 3.0.7 on 2021-05-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapegeom',
            old_name='shape_id',
            new_name='shape',
        ),
        migrations.AddField(
            model_name='requestfiles',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requestfiles',
            name='tools',
            field=models.TextField(default=''),
        ),
    ]
