# Generated by Django 3.0.7 on 2021-05-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0003_auto_20210526_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_org', models.CharField(max_length=100, verbose_name='Нэр')),
                ('project_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('object_type', models.TextField()),
                ('object_quantum', models.TextField()),
                ('investment_status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llc_request.RequestFiles')),
            ],
            options={
                'db_table': 'llc_request_form',
            },
        ),
    ]
