# Generated by Django 3.0.7 on 2021-05-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0004_requestform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='forms',
            new_name='file',
        ),
    ]
