# Generated by Django 3.0.7 on 2021-06-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0006_auto_20210529_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfiles',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ИЛГЭЭСЭН')], db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='LLCRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveIntegerField(choices=[(1, 'ШИЙДВЭРЛЭГДСЭН'), (2, 'ХҮЛЭЭГДЭЖ БУЙ'), (3, 'БУЦААГДСАН'), (4, 'ЦУЦЛАСАН'), (5, 'ШИНЭ')], db_index=True, null=True)),
                ('state', models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ИЛГЭЭСЭН')], db_index=True, null=True)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llc_request.RequestFiles')),
            ],
            options={
                'db_table': 'llc_request',
            },
        ),
    ]
