# Generated by Django 3.0.7 on 2021-06-04 07:47

from django.db import migrations, models
import llc.backend.llc_request.models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0007_auto_20210602_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfiles',
            name='file_path',
            field=models.FileField(upload_to=llc.backend.llc_request.models.upload_file_path),
        ),
    ]
