# Generated by Django 3.0.7 on 2021-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0008_auto_20210604_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfilesshape',
            name='order_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestfilesshape',
            name='order_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
