# Generated by Django 3.0.7 on 2021-06-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0009_auto_20210608_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llcrequest',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'БАТАЛГААЖСАН'), (2, 'ХҮЛЭЭГДЭЖ БУЙ'), (3, 'БУЦААГДСАН'), (4, 'ЦУЦЛАСАН'), (5, 'ШИНЭ')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='llcrequest',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ИЛГЭЭСЭН'), (3, 'ШИЙДВЭРЛЭГДСЭН')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestfiles',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'БАТАЛГААЖСАН'), (2, 'ХҮЛЭЭГДЭЖ БУЙ'), (3, 'БУЦААГДСАН'), (4, 'ЦУЦЛАСАН'), (5, 'ШИНЭ')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestfiles',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ИЛГЭЭСЭН'), (3, 'ШИЙДВЭРЛЭГДСЭН')], db_index=True, null=True),
        ),
    ]
