# Generated by Django 3.0.7 on 2021-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0011_change_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfilesshape',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'ХҮЛЭЭГДЭЖ БУЙ'), (2, 'БАТАЛГААЖСАН'), (3, 'БУЦААГДСАН'), (4, 'ЦУЦЛАСАН')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='requestfilesshape',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ИЛГЭЭСЭН'), (3, 'ШИЙДВЭРЛЭГДСЭН')], db_index=True, null=True),
        ),
    ]
