# Generated by Django 3.0.7 on 2021-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0011_change_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='investment_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
