# Generated by Django 3.0.7 on 2021-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0013_delete_old_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='investment_status',
            field=models.PositiveIntegerField(choices=[(1, 'ТӨСӨЛ, ХӨТӨЛБӨРИЙН'), (2, 'ОРОН НУТГИЙН'), (3, 'УЛСЫН ТӨСВИЙН'), (4, 'ХУВИЙН')], db_index=True, null=True),
        ),
    ]
