# Generated by Django 3.0.7 on 2021-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0015_auto_20210625_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfiles',
            name='requested_employee',
            field=models.IntegerField(null=True),
        ),
    ]
