# Generated by Django 3.0.7 on 2021-06-29 06:37
import os
from django.conf import settings
from django.db import migrations
from main import utils


def remove_solved_request(apps, schema_editor):

    STATE_SOLVED = 3
    main_folder = 'llc-request-files'
    RequestFiles = apps.get_model('llc_request', 'RequestFiles')
    file_qs = RequestFiles.objects.filter(state=STATE_SOLVED)
    if file_qs:
        for file in file_qs:
            file_path = str(file.file_path)
            if file_path:
                file_path = file_path.split('/')
                remove_folder = os.path.join(settings.MEDIA_ROOT, main_folder, file_path[1])
                if os.path.exists(remove_folder):
                    utils.remove_folder(remove_folder)
                file.file_path = None
                file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('llc_request', '0015_auto_20210625_1809'),
    ]

    operations = [
         migrations.RunPython(remove_solved_request),
    ]
