# Generated by Django 3.0.7 on 2020-10-28 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_org', '0006_auto_20201026_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('feature_id', models.IntegerField()),
                ('state', models.PositiveIntegerField(choices=[(1, 'Шинээр үүссэн'), (2, 'Цуцлах'), (3, 'Хянах'), (4, 'Батлах')], db_index=True, null=True)),
                ('form_json', models.TextField(null=True)),
                ('geo_json', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_org.Employee')),
            ],
        ),
    ]
