# Generated by Django 3.0.7 on 2020-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0003_auto_20201029_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ТАТГАЛЗСАН'), (3, 'ЗӨВШӨӨРСӨН')], db_index=True, null=True),
        ),
    ]
