# Generated by Django 3.0.7 on 2020-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0007_remove_changerequest_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='order_at',
            field=models.DateTimeField(null=True),
        ),
    ]
