# Generated by Django 3.0.7 on 2020-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0008_auto_20201119_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'ҮҮССЭН'), (2, 'ЗАССАН'), (3, 'УСТГАСАН'), (5, 'ЦУЦЛАХ'), (4, 'ШУУД')], db_index=True, null=True),
        ),
    ]
