# Generated by Django 3.0.7 on 2020-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0008_auto_20201119_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='state',
            field=models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ТАТГАЛЗСАН'), (3, 'ЗӨВШӨӨРСӨН'), (4, 'ХЯНАХ')], db_index=True, null=True),
        ),
    ]
