# Generated by Django 3.0.7 on 2020-12-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0009_auto_20201204_1600'),
        ('org_request', '0009_auto_20201128_0917'),
    ]

    operations = [
    ]
