# Generated by Django 3.0.7 on 2021-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0010_update_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'ҮҮССЭН'), (3, 'УСТГАСАН'), (2, 'ЗАССАН'), (4, 'ШУУД')], db_index=True, null=True),
        ),
    ]
