# Generated by Django 3.0.7 on 2021-02-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0016_delete_inspireperm'),
        ('org_request', '0013_g_changereq_update_geom_and_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org'),
            preserve_default=False,
        ),
    ]
