# Generated by Django 3.0.7 on 2021-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0016_auto_20210201_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'ҮҮССЭН'), (2, 'ЗАССАН'), (3, 'УСТГАСАН'), (4, 'ШУУД'), (5, 'ЦУЦЛАСАН')], db_index=True, null=True),
        ),
    ]
