# Generated by Django 3.0.7 on 2021-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0017_auto_20210205_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'ҮҮССЭН'), (2, 'ЗАССАН'), (3, 'УСТГАСАН'), (4, 'ШУУД'), (5, 'ЦУЦЛАСАН'), (6, 'Буцаагдсан')], db_index=True, null=True),
        ),
    ]
