# Generated by Django 3.0.7 on 2021-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_request', '0019_auto_20210604_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
