# Generated by Django 3.0.7 on 2020-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('onlineResource', models.CharField(max_length=500)),
                ('imgformat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.AddField(
            model_name='wms',
            name='styles',
            field=models.ManyToManyField(to='backend_wms.Style'),
        ),
    ]
