# Generated by Django 3.0.7 on 2020-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0002_auto_20200630_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='wms',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
