# Generated by Django 3.0.7 on 2020-12-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_org', '0013_employee_create_token'),
        ('backend_wms', '0004_wmslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
