# Generated by Django 3.0.7 on 2020-12-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0013_merge_20201204_1341'),
        ('backend_wms', '0004_wmslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Employee'),
        ),
    ]
