# Generated by Django 3.0.7 on 2021-02-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0005_wmslog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wms',
            name='cache_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
