# Generated by Django 3.0.7 on 2021-05-03 06:32

from django.db import migrations


def set_link(apps, schema_editor):
    print('\nУншиж байна ...')
    WMS = apps.get_model('backend_wms', 'WMS')
    qs = WMS.objects.all()
    for wms in qs:
        if 'http://nsdi.gov.mn:8080/geoserver/' in wms.url:
            url = wms.url
            splited_url = url.split('http://nsdi.gov.mn:8080/geoserver')
            if 1 < len(splited_url):
               use_url = 'https://geo.nsdi.gov.mn' + splited_url[1]
               wms.url = use_url
        if wms.cache_url:
            cache_url = wms.cache_url
            if 'http://nsdi.gov.mn:8080/geoserver/' in wms.cache_url:
                splited_url = cache_url.split('http://nsdi.gov.mn:8080/geoserver')
                if 1 < len(splited_url):
                    use_cache_url = 'https://geo.nsdi.gov.mn' + splited_url[1]
                    wms.cache_url = use_cache_url
            if 'http://192.168.10.15:8080/geoserver/' in wms.cache_url:
                splited_url = cache_url.split('http://192.168.10.15:8080/geoserver')
                if 1 < len(splited_url):
                    use_cache_url = 'http://192.168.10.15:8080' + splited_url[1]
                    wms.cache_url = use_cache_url
        wms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0008_auto_20210503_1217'),
    ]

    operations = [
        migrations.RunPython(set_link),
    ]
