# Generated by Django 3.0.7 on 2021-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0009_auto_20210503_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslog',
            name='wms',
        ),
        migrations.AddField(
            model_name='wmslog',
            name='wms_id',
            field=models.IntegerField(null=True),
        ),
    ]
