# Generated by Django 3.0.7 on 2021-05-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wms', '0010_auto_20210512_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmslog',
            name='wms_id',
        ),
    ]
