# Generated by Django 3.0.7 on 2020-08-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsegUstsan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('alban_tushaal', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('tseg_id', models.CharField(max_length=300)),
                ('oiroltsoo_bairlal', models.CharField(max_length=300)),
                ('evdersen_baidal', models.CharField(max_length=300)),
                ('shaltgaan', models.CharField(max_length=1000)),
                ('img_holoos', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_oiroos', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_baruun', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_zuun', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_hoino', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_omno', models.ImageField(upload_to='tseg-ustsan/')),
                ('sergeeh_sanal', models.CharField(max_length=100)),
                ('gps_hemjilt', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
