# Generated by Django 3.0.7 on 2020-08-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuuhenov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsegPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesgiin_ner', models.CharField(max_length=50)),
                ('toviin_dugaar', models.CharField(max_length=100)),
                ('trapetsiin_dugaar', models.CharField(max_length=100)),
                ('suljeenii_torol', models.CharField(max_length=20)),
                ('aimag_name', models.CharField(max_length=30)),
                ('sum_name', models.CharField(max_length=30)),
                ('utmx', models.CharField(max_length=50)),
                ('utmy', models.CharField(max_length=50)),
                ('latlongx', models.CharField(max_length=100)),
                ('latlongy', models.CharField(max_length=100)),
                ('tseg_oiroos_img_url', models.ImageField(upload_to='tseg-personal/')),
                ('tseg_holoos_img_url', models.ImageField(upload_to='tseg-personal/')),
                ('barishil_tuhai', models.CharField(max_length=1000)),
                ('bairshil_tseg_oiroos_img_url', models.ImageField(upload_to='tseg-personal-img/')),
                ('bairshil_tseg_holoos_img_url', models.ImageField(upload_to='tseg-personal-img/')),
                ('sudalga_or_shine', models.CharField(max_length=30)),
                ('hors_shinj_baidal', models.CharField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
                ('hotolson', models.CharField(max_length=100)),
                ('file_path1', models.FileField(upload_to='tseg-personal-file/')),
                ('file_path2', models.FileField(upload_to='tseg-personal-file/')),
                ('alban_tushaal', models.CharField(max_length=200)),
                ('alban_baiguullga', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
