# Generated by Django 3.0.7 on 2020-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuuhenov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuuhsoyolayuulhuree',
            name='utmx',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuuhsoyolayuulhuree',
            name='utmy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuuhsoyolhuree',
            name='utmx',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuuhsoyolhuree',
            name='utmy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
