# Generated by Django 3.0.7 on 2020-08-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuuhenov', '0003_dursgaltgazar_tuuhsoyol_tuuhsoyolayuulhuree_tuuhsoyolhuree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuuhsoyol',
            name='descriptio',
        ),
        migrations.AddField(
            model_name='dursgaltgazar',
            name='descriptio',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
