# Generated by Django 3.0.7 on 2020-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuuhenov', '0004_auto_20200827_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dursgaltgazar',
            old_name='type',
            new_name='type1',
        ),
        migrations.AddField(
            model_name='dursgaltgazar',
            name='type2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dursgaltgazar',
            name='utm_x',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dursgaltgazar',
            name='utm_y',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dursgaltgazar',
            name='utm_zone',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
