# Generated by Django 3.0.6 on 2020-07-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_govorg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govorg',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelTable(
            name='govorg',
            table='govorg',
        ),
    ]
