# Generated by Django 3.0.6 on 2020-07-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0004_auto_20200705_2118'),
        ('backend_govorg', '0002_auto_20200705_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovOrgWMSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('govorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_govorg.GovOrg')),
                ('wms_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_wmslayer.WMSLayer')),
            ],
        ),
        migrations.AddField(
            model_name='govorg',
            name='wms_layers',
            field=models.ManyToManyField(related_name='govorgs', through='backend_govorg.GovOrgWMSLayer', to='backend_wmslayer.WMSLayer'),
        ),
    ]
