# Generated by Django 3.0.6 on 2020-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_govorg', '0003_auto_20200705_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govorg',
            name='token',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
