# Generated by Django 3.0.7 on 2020-08-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0001_initial'),
        ('backend_govorg', '0004_auto_20200708_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='govorg',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org'),
        ),
    ]
