# Generated by Django 3.0.7 on 2021-03-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_govorg', '0009_update_geoserver__crs'),
    ]

    operations = [
        migrations.AddField(
            model_name='govorgwmslayer',
            name='attributes',
            field=models.TextField(null=True),
        ),
    ]
