# Generated by Django 3.0.7 on 2021-07-28 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0010_remove_wmslayer_legend_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_org', '0028_auto_20210616_1300'),
        ('backend_wms', '0011_remove_wmslog_wms_id'),
        ('backend_govorg', '0010_govorgwmslayer_attributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GovOrg',
            new_name='System',
        ),
        migrations.RenameField(
            model_name='govorgwmslayer',
            old_name='govorg',
            new_name='system',
        ),
        migrations.AlterModelTable(
            name='system',
            table='system',
        ),
    ]
