# Generated by Django 3.0.7 on 2021-03-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_org', '0025_nemawms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidDashboardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Нэр')),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('geo_id', models.CharField(db_index=True, max_length=250, null=True)),
                ('batlagdsan_tohioldol_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Батлагдсан тохиолдол')),
                ('edgersen_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эдгэрсэн хүмүүсийн тоо')),
                ('emchlegdej_bui_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмчлэгдэж буй хүмүүсийн тоо')),
                ('nas_barsan_hunii_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Нас барсан хүмүүсийн тоо')),
                ('tusgaarlagdaj_bui_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Тусгаарлагдаж буй хүмүүсийн тоо')),
                ('niit_eruul_mendiin_baiguullaga_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Нийт эрүүл мэндийн байгууллагын тоо')),
                ('emnelegiin_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмнэлэгийн тоо')),
                ('emiin_sangiin_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмийн сангийн тоо')),
                ('shinjilgee_hiisen_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Шинжилгээ хийсэн тоо')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Бүртгэсэн огноо')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org', verbose_name='Байгууллага')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн ажилтан')),
            ],
            options={
                'db_table': 'covid_dashboard_log',
            },
        ),
        migrations.CreateModel(
            name='CovidDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Нэр')),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('geo_id', models.CharField(db_index=True, max_length=250, null=True)),
                ('batlagdsan_tohioldol_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Батлагдсан тохиолдол')),
                ('edgersen_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эдгэрсэн хүмүүсийн тоо')),
                ('emchlegdej_bui_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмчлэгдэж буй хүмүүсийн тоо')),
                ('nas_barsan_hunii_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Нас барсан хүмүүсийн тоо')),
                ('tusgaarlagdaj_bui_humuus_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Тусгаарлагдаж буй хүмүүсийн тоо')),
                ('niit_eruul_mendiin_baiguullaga_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Нийт эрүүл мэндийн байгууллагын тоо')),
                ('emnelegiin_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмнэлэгийн тоо')),
                ('emiin_sangiin_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Эмийн сангийн тоо')),
                ('shinjilgee_hiisen_too', models.PositiveIntegerField(default=0, null=True, verbose_name='Шинжилгээ хийсэн тоо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Бүртгэсэн огноо')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org', verbose_name='Байгууллага')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэсэн ажилтан')),
            ],
            options={
                'db_table': 'covid_dashboard',
            },
        ),
    ]
