# Generated by Django 3.0.7 on 2021-03-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_covid', '0003_auto_20210319_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='coviddashboardlog',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Бүртгэсэн огноо'),
        ),
        migrations.CreateModel(
            name='PopulationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('code', models.PositiveIntegerField()),
                ('total_number', models.PositiveIntegerField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontend_covid.PopulationAge')),
            ],
        ),
    ]
