# Generated by Django 3.0.7 on 2021-03-20 07:08

from django.db import migrations
from main import utils


def _fix_query(Model):
    qs = Model.objects
    qs = qs.filter(geo_id__icontains='au')
    if qs:
        for item in qs:
            if item.geo_id:
                new_geo_id = item.geo_id.replace('au_', '')
                item.geo_id = new_geo_id
                item.save()


def _fix_data(apps, schema):
    CovidDashboard = apps.get_model('frontend_covid', 'CovidDashboard')

    _fix_query(CovidDashboard)

    CovidDashboardLog = apps.get_model('frontend_covid', 'CovidDashboardLog')

    _fix_query(CovidDashboardLog)

    Org = apps.get_model('backend_org', 'Org')

    _fix_query(Org)


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_covid', '0003_auto_20210319_1043'),
    ]

    operations = [
        migrations.RunPython(_fix_data),
    ]