# Generated by Django 3.0.7 on 2021-03-20 07:08

from django.db import migrations


def _fix_query(Model):
    qs = Model.objects
    qs = qs.filter(geo_id='au_496')
    if qs:
        qs.update(geo_id='496')


def _fix_data(apps, schema):
    CovidDashboard = apps.get_model('frontend_covid', 'CovidDashboard')

    _fix_query(CovidDashboard)

    CovidDashboardLog = apps.get_model('frontend_covid', 'CovidDashboardLog')

    _fix_query(CovidDashboardLog)


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_covid', '0003_auto_20210319_1043'),
    ]

    operations = [
        migrations.RunPython(_fix_data),
    ]