# Generated by Django 3.0.7 on 2021-03-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_covid', '0004_auto_20210320_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddashboardlog',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Бүртгэсэн огноо'),
        ),
    ]
