# Generated by Django 3.0.6 on 2020-06-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_wmslayer', '0001_initial'),
        ('backend_bundle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlelayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer', to='backend_wmslayer.WMSLayer'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='layers',
            field=models.ManyToManyField(related_name='bundlelayer', through='backend_bundle.BundleLayer', to='backend_wmslayer.WMSLayer'),
        ),
    ]
