# Generated by Django 3.0.6 on 2020-06-01 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_bundle', '0002_auto_20200601_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bundle',
            name='layers',
            field=models.ManyToManyField(through='backend_bundle.BundleLayer', to='backend_wmslayer.WMSLayer'),
        ),
        migrations.AlterField(
            model_name='bundlelayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_wmslayer.WMSLayer'),
        ),
    ]
