# Generated by Django 3.0.6 on 2020-06-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0003_auto_20200601_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='icon',
            field=models.ImageField(default='дэд-сан/sub-1.png', upload_to='дэд-сан/'),
            preserve_default=False,
        ),
    ]
