# Generated by Django 3.0.6 on 2020-06-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0004_bundle_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='bundle',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
