# Generated by Django 3.0.7 on 2020-06-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0007_auto_20200627_1806'),
        ('backend_bundle', '0007_auto_20200612_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlelayer',
            name='defaultCheck',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundlelayer',
            name='role',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='geoportal_app.Role'),
        ),
    ]
