# Generated by Django 3.0.7 on 2020-09-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0007_auto_20200623_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='price',
        ),
        migrations.AddField(
            model_name='bundle',
            name='modul',
            field=models.PositiveIntegerField(choices=[(1, 'Түүх, соёлын өв')], db_index=True, null=True),
        ),
    ]
