# Generated by Django 3.0.7 on 2020-09-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0008_bundle_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='module',
            field=models.PositiveIntegerField(choices=[(1, 'Түүх, соёлын өв'), (2, 'Геодезийн тулгуур сүлжээ')], db_index=True, null=True),
        ),
    ]
