# Generated by Django 3.0.7 on 2020-06-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0006_auto_20200614_1338'),
        ('backend_bundle', '0008_auto_20200621_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlelayer',
            name='defaultCheck',
        ),
        migrations.RemoveField(
            model_name='bundlelayer',
            name='role',
        ),
        migrations.CreateModel(
            name='AdminRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultCheck', models.PositiveIntegerField()),
                ('bundleLayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_bundle.BundleLayer')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoportal_app.Role')),
            ],
        ),
    ]
