# Generated by Django 3.0.7 on 2020-06-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0006_auto_20200614_1338'),
        ('backend_bundle', '0009_auto_20200621_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlelayer',
            name='defaultCheck',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bundlelayer',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geoportal_app.Role'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdminRights',
        ),
    ]
