# Generated by Django 3.0.7 on 2020-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0009_auto_20200918_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='module',
            field=models.PositiveIntegerField(choices=[(1, 'Түүх, соёлын өв'), (2, 'Геодезийн тулгуур сүлжээ'), (3, 'Тээврийн сүлжээ'), (4, 'Дэд бүтэц'), (5, 'Байр зүйн зураг'), (6, 'Барилга, суурин газар')], db_index=True, null=True),
        ),
    ]
