# Generated by Django 3.0.7 on 2020-11-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0012_bundlegis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='price',
        ),
    ]
