# Generated by Django 3.0.7 on 2020-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0013_auto_20200621_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlelayer',
            name='defaultCheck',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
