# Generated by Django 3.0.7 on 2020-11-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0005_auto_20201117_1056'),
        ('backend_bundle', '0014_auto_20201117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='ltheme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_inspire.LThemes'),
        ),
    ]
