# Generated by Django 3.0.7 on 2020-11-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0016_bundle_lthemes_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='name',
        ),
    ]
