# Generated by Django 3.0.7 on 2020-06-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0017_auto_20200621_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlelayer',
            name='defaultCheck',
        ),
        migrations.RemoveField(
            model_name='bundlelayer',
            name='role',
        ),
    ]
