# Generated by Django 3.0.7 on 2020-06-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal_app', '0006_auto_20200614_1338'),
        ('backend_bundle', '0019_auto_20200621_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlelayer',
            name='defaultCheck',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bundlelayer',
            name='role',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='geoportal_app.Role'),
        ),
    ]
