# Generated by Django 3.0.7 on 2021-06-13 10:02

from django.db import migrations

def make_bundle_same_as_theme(apps, schema_editor):
    print('\nУншиж байна ...')
    Bundle = apps.get_model('backend_bundle', 'Bundle')
    LThemes = apps.get_model('backend_inspire', 'LThemes')

    change_values = [
        "Геодезийн цэг тэмдэгт", "Байр зүйн зураг", "Хил зааг", "Хаяг",
        "Барилга, суурин газар", "Өндөржилт, гүн", "Газар зүйн нэр", "Газар ашиглалт",
        "Газрын бүрхэвч", "Газрын нэгж талбар", "Дэд бүтэц", "Тээврийн сүлжээ",
        "Ус зүйн мэдээлэл", "Ортозураг", "Хөрс", "Геологи",
        "Хүн ам зүйн мэдээлэл", "Түүх соёл, археологийн өв"
    ]

    themes = LThemes.objects.all().values_list('theme_id', flat=True)
    for theme in themes:
        bundle = Bundle.objects.filter(ltheme_id=theme)
        if not bundle:
            print(theme)


    raise Exception('lol')


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0019_make_id_index'),
    ]

    operations = [
        migrations.RunPython(make_bundle_same_as_theme),
    ]


