# Generated by Django 3.0.7 on 2021-07-22 03:07

from django.db import migrations

def bundle_sort_order_to_theme_id(apps, schema_editor):
    print('\nУншиж байна ...')

    Bundle = apps.get_model('backend_bundle', 'Bundle')

    qs_bundle = Bundle.objects
    for bundle in qs_bundle.all():
        theme_id = bundle.ltheme_id
        if theme_id:
            bundle.sort_order = theme_id
            bundle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0020_auto_20210613_1802'),
    ]

    operations = [
        migrations.RunPython(bundle_sort_order_to_theme_id),
    ]
