# Generated by Django 3.0.7 on 2021-02-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedsanbutets', '0002_update_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureOverlaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('overlap_feature_id', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
