# Generated by Django 3.0.7 on 2021-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedsanbutets', '0004_auto_20210608_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewnames',
            name='open_datas',
            field=models.TextField(default=None, null=True),
        ),
    ]
