# Generated by Django 3.0.7 on 2021-07-27 06:50

from django.db import migrations, models
import django.db.models.deletion
from django.core.cache import cache
from django.db import connections


VIEWNAME_CACHE_KEY = 'view_names_datas'
VIEWPROPERTIES_CACHE_KEY = 'view_properties_datas'


def _saveDatas(apps, schema):
    ViewNames = apps.get_model('dedsanbutets', 'ViewNames')
    ViewProperties = apps.get_model('dedsanbutets', 'ViewProperties')

    view_names_datas = list(ViewNames.objects.values('id', 'feature_id'))
    cache.set(VIEWNAME_CACHE_KEY, view_names_datas, 300)
    print("\n")
    print('\x1b[6;30;42m' + '...ViewNames ийн датаг хадгалж авлаа...' + '\x1b[0m')

    view_properties_datas = list(ViewProperties.objects.values('id', 'property_id'))
    cache.set(VIEWPROPERTIES_CACHE_KEY, view_properties_datas, 300)
    print('\x1b[6;30;42m' + '...ViewProperty ийн датаг хадгалж авлаа...' + '\x1b[0m')


def _insertDatas(apps, schema):
    ViewNames = apps.get_model('dedsanbutets', 'ViewNames')
    ViewProperties = apps.get_model('dedsanbutets', 'ViewProperties')

    print("\n")
    print('\33[94m' + "ViewNames ийн датаг оруулж эхэллээ" + '\33[0m')

    view_names_datas = cache.get(VIEWNAME_CACHE_KEY)
    for view_data in view_names_datas:
        qs = ViewNames.objects
        qs = qs.filter(id=view_data['id'])
        del view_data['id']
        qs.update(**view_data)

    print('\x1b[6;30;42m' + 'ViewNames ийн датаг оруулж дууслаа' + '\x1b[0m')

    view_property_datas = cache.get(VIEWPROPERTIES_CACHE_KEY)
    for view_prop_data in view_property_datas:
        qs = ViewProperties.objects
        qs = qs.filter(id=view_prop_data['id'])
        del view_prop_data['id']
        qs.update(**view_prop_data)


def _create_pk(table, cursor):
    obj = {
        'l_properties': ['l_properties_pkey', 'property_id'],
        'l_data_types': ['l_data_types_pkey', 'data_type_id'],
        'l_features': ['l_features_pkey', 'feature_id'],
    }
    pkey_name, field_name = obj[table]
    sql = """
        ALTER TABLE {}
        ADD CONSTRAINT {}
        PRIMARY KEY ({});
    """.format(table, pkey_name, field_name)
    cursor.execute(sql)


def _check_pk(apps, schema_editor):
    LProperties = apps.get_model('backend_inspire', 'LProperties')
    tables = ['l_data_types', 'l_features', 'l_properties']

    unneed_properties = LProperties.objects.filter(property_id=0)
    if len(unneed_properties) > 1:
        unneed_properties.delete()

    cursor = connections['default'].cursor()
    for table in tables:
        sql = """
            SELECT c.column_name, c.data_type
            FROM information_schema.table_constraints tc
            JOIN information_schema.constraint_column_usage AS ccu USING (constraint_schema, constraint_name)
            JOIN information_schema.columns AS c ON c.table_schema = tc.constraint_schema
            AND tc.table_name = c.table_name AND ccu.column_name = c.column_name
            WHERE constraint_type = 'PRIMARY KEY' and tc.table_name = '{}';
        """.format(table)
        cursor.execute(sql)
        value = cursor.fetchone()
        if not value:
            _create_pk(table, cursor)



class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0013_auto_20210728_1001'),
        ('dedsanbutets', '0005_viewnames_open_datas'),
    ]

    operations = [
        migrations.RunPython(_check_pk),
        migrations.RunPython(_saveDatas),
        migrations.RemoveField(
            model_name='viewnames',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='viewproperties',
            name='property_id',
        ),
        migrations.AddField(
            model_name='viewnames',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LFeatures'),
        ),
        migrations.AddField(
            model_name='viewproperties',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LProperties'),
        ),
        migrations.RunPython(_insertDatas),
    ]
