# Generated by Django 3.0.7 on 2021-07-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_inspire', '0013_auto_20210727_1450'),
        ('dedsanbutets', '0005_viewnames_open_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewnames',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='viewproperties',
            name='property_id',
        ),
        migrations.AddField(
            model_name='viewnames',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LFeatures'),
        ),
        migrations.AddField(
            model_name='viewproperties',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_inspire.LProperties'),
        ),
    ]
