# Generated by Django 3.0.7 on 2020-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200827_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuuhsoyolayuulhuree',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuuhsoyolhuree',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
