# Generated by Django 3.0.7 on 2020-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200827_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='geom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='geom',
            field=models.CharField(max_length=150),
        ),
    ]
