# Generated by Django 3.0.7 on 2020-09-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200902_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuuhSoyolPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.CharField(max_length=150)),
                ('latlong', models.CharField(max_length=100)),
                ('dursgal', models.CharField(max_length=100)),
                ('dursgal2', models.CharField(max_length=100)),
                ('descriptio', models.CharField(max_length=150)),
                ('type1', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=200)),
                ('stone', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=20)),
                ('hight', models.CharField(max_length=20)),
                ('depth', models.CharField(max_length=20)),
                ('meridian', models.CharField(max_length=20)),
                ('other', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('hemjee_comment', models.CharField(max_length=500)),
                ('protection_irgen', models.CharField(max_length=100)),
                ('protection_irgen_commnent', models.CharField(max_length=1000)),
                ('protection', models.CharField(max_length=100)),
                ('protecti_1', models.CharField(max_length=100)),
                ('tus', models.CharField(max_length=10)),
                ('tus_comment', models.CharField(max_length=500)),
                ('yaral', models.CharField(max_length=100)),
                ('yaral_comment', models.CharField(max_length=500)),
                ('omchlol', models.CharField(max_length=100)),
                ('omchlol_comment', models.CharField(max_length=500)),
                ('malts', models.CharField(max_length=100)),
                ('malts_comment', models.CharField(max_length=500)),
                ('human', models.CharField(max_length=100)),
                ('human_comment', models.CharField(max_length=500)),
                ('natural', models.CharField(max_length=100)),
                ('natural_comment', models.CharField(max_length=500)),
                ('recover', models.CharField(max_length=100)),
                ('recover_comment', models.CharField(max_length=500)),
                ('recover1', models.CharField(max_length=100)),
                ('recover1_comment', models.CharField(max_length=500)),
                ('protecti_2', models.CharField(max_length=100)),
                ('protecti_2_comment', models.CharField(max_length=500)),
                ('hashaa', models.CharField(max_length=100)),
                ('hashaa_comment', models.CharField(max_length=500)),
                ('saravch', models.CharField(max_length=100)),
                ('saravch_comment', models.CharField(max_length=500)),
                ('hayg', models.CharField(max_length=100)),
                ('hayg_comment', models.CharField(max_length=500)),
                ('other1', models.CharField(max_length=100)),
                ('utm', models.CharField(max_length=100)),
                ('ndd', models.BigIntegerField()),
                ('nmm', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('nss', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('edd', models.BigIntegerField()),
                ('emm', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('ess', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('x', models.CharField(max_length=50)),
                ('y', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=100)),
                ('utm_zone', models.CharField(max_length=50)),
                ('utm_x', models.CharField(max_length=50)),
                ('utm_y', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tuuhsoyol',
            name='aimagname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tuuhsoyol',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tuuhsoyol',
            name='inspireid',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tuuhsoyol',
            name='sumname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tuuhsoyol',
            name='too_shirheg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='edd',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='emm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='ess',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='ndd',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='nmm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='nss',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='edd',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='emm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='ess',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='ndd',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='nmm',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='nss',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.DeleteModel(
            name='DursgaltGazar',
        ),
        migrations.AddField(
            model_name='tuuhsoyolpoint',
            name='tuuh_soyl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.TuuhSoyol'),
        ),
    ]
