# Generated by Django 3.0.7 on 2020-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200903_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolpoint',
            name='geom',
        ),
        migrations.AddField(
            model_name='tuuhsoyolpoint',
            name='area',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
