# Generated by Django 3.0.7 on 2020-09-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200904_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuuhsoyolhuree',
            name='tuuh_soyl_huree_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
