# Generated by Django 3.0.7 on 2020-09-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200904_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tuuhsoyol',
            table='tuuhsoyol',
        ),
        migrations.AlterModelTable(
            name='tuuhsoyolayuulhuree',
            table='tuuhsoyolayuulhuree',
        ),
        migrations.AlterModelTable(
            name='tuuhsoyolhuree',
            table='tuuhsoyolhuree',
        ),
        migrations.AlterModelTable(
            name='tuuhsoyolpoint',
            table='tuuhsoyolpoint',
        ),
    ]
