# Generated by Django 3.0.7 on 2020-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_changeset', '0002_auto_20201001_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='projection',
            field=models.CharField(default='EPSG:4326', max_length=50),
            preserve_default=False,
        ),
    ]
