# Generated by Django 3.0.7 on 2020-08-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200811_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='success_at',
            field=models.DateTimeField(null=True),
        ),
    ]
