# Generated by Django 3.0.7 on 2020-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200811_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coodrinatLeftTop',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='coodrinatRightBottom',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
