# Generated by Django 3.0.7 on 2020-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200821_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coodrinatLeftTopX',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='coodrinatLeftTopY',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='coodrinatRightBottomX',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='coodrinatRightBottomY',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
