# Generated by Django 3.0.7 on 2020-09-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200822_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='error_message',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='error_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coodrinatLeftTopX',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coodrinatLeftTopY',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coodrinatRightBottomX',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='coodrinatRightBottomY',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='data_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='message',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100)),
                ('pdf_id', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('coodrinatLeftTopX', models.DecimalField(decimal_places=10, max_digits=20)),
                ('coodrinatLeftTopY', models.DecimalField(decimal_places=10, max_digits=20)),
                ('coodrinatRightBottomX', models.DecimalField(decimal_places=10, max_digits=20)),
                ('coodrinatRightBottomY', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=100)),
                ('point_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('pdf_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
            ],
        ),
    ]
