# Generated by Django 3.0.7 on 2020-09-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_wmslayer', '0006_auto_20200723_0853'),
        ('payment', '0006_auto_20200911_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='export_kind',
            field=models.PositiveIntegerField(choices=[(1, 'Цэг'), (2, 'Полигон')], db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.PositiveIntegerField(choices=[(1, 'Монгол Банк'), (2, 'QPay')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mongolbank_rsp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qpay_rsp',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PaymentLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultCheck', models.PositiveIntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
                ('wms_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_wmslayer.WMSLayer')),
            ],
        ),
    ]
