# Generated by Django 3.0.7 on 2020-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200913_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='export_file',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
