# Generated by Django 3.0.7 on 2020-09-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bundle', '0007_auto_20200623_1517'),
        ('payment', '0008_payment_export_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bundle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_bundle.Bundle'),
        ),
    ]
