# Generated by Django 3.0.7 on 2021-02-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20210210_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ext_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
