# Generated by Django 3.0.7 on 2020-09-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpoint',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('objectid', models.BigIntegerField()),
                ('point_id', models.CharField(max_length=10)),
                ('point_name', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=20)),
                ('point_class', models.BigIntegerField()),
                ('point_type', models.CharField(max_length=100)),
                ('center_typ', models.CharField(max_length=10)),
                ('aimag', models.CharField(max_length=50)),
                ('sum', models.CharField(max_length=50)),
                ('sheet1', models.CharField(max_length=1)),
                ('sheet2', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('sheet3', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('geom', models.DecimalField(decimal_places=10, max_digits=300)),
                ('t_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mpoint',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tsegpersonal',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
