# Generated by Django 3.0.7 on 2020-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_tuuhsoyolhuree_tuuh_soyl_huree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuuhsoyolayuulhuree',
            name='tuuh_soyl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolhuree',
            name='tuuh_soyl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tuuhsoyolpoint',
            name='tuuh_soyl',
            field=models.CharField(max_length=100),
        ),
    ]
