# Generated by Django 3.0.7 on 2020-09-04 12:59

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200904_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuuhsoyol',
            options={'managed': settings.IS_TESTING},
        ),
        migrations.AlterModelOptions(
            name='tuuhsoyolayuulhuree',
            options={'managed': settings.IS_TESTING},
        ),
        migrations.AlterModelOptions(
            name='tuuhsoyolhuree',
            options={'managed': settings.IS_TESTING},
        ),
        migrations.AlterModelOptions(
            name='tuuhsoyolpoint',
            options={'managed': settings.IS_TESTING},
        ),
    ]
