# Generated by Django 3.0.7 on 2020-09-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20200904_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuuhsoyolayuulhuree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tuuhsoyolhuree',
            options={},
        ),
    ]
