# Generated by Django 3.0.7 on 2020-09-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20200906_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='edd',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='emm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='ess',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='latlong',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='ndd',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='nmm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='utm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='utmx',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolayuulhuree',
            name='utmy',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='edd',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='emm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='ess',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='latlong',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='ndd',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='nmm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='utm',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='utmx',
        ),
        migrations.RemoveField(
            model_name='tuuhsoyolhuree',
            name='utmy',
        ),
    ]
