# Generated by Django 3.0.7 on 2020-09-06 11:29

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20200906_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuuhSoyolAyuulHureePol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuuh_soyl', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tuuhsoyolayuulhureepol',
                'managed': settings.IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name='TuuhSoyolHureePol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuuh_soyl', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tuuhsoyolhureepol',
                'managed': settings.IS_TESTING,
            },
        ),
    ]
