# Generated by Django 3.0.7 on 2020-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_tuuhsoyolayuulhureepol_tuuhsoyolhureepol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsegUstsanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=100)),
                ('img_holoos', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_oiroos', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_baruun', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_zuun', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_hoino', models.ImageField(upload_to='tseg-ustsan/')),
                ('img_omno', models.ImageField(upload_to='tseg-ustsan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
