# Generated by Django 3.0.7 on 2021-03-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_org', '0025_nemawms'),
        ('forms', '0017_mpoint10'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsegRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_geo_id', models.CharField(max_length=100, null=True)),
                ('new_geo_id', models.CharField(max_length=100, null=True)),
                ('theme_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('feature_id', models.IntegerField()),
                ('state', models.PositiveIntegerField(choices=[(1, 'ШИНЭ'), (2, 'ТАТГАЛЗСАН'), (3, 'ЗӨВШӨӨРСӨН')], db_index=True, null=True)),
                ('kind', models.PositiveIntegerField(choices=[(1, 'ҮҮССЭН'), (2, 'ЗАССАН'), (3, 'УСТГАСАН')], db_index=True, null=True)),
                ('values', models.TextField(null=True)),
                ('form_json', models.TextField(null=True)),
                ('geo_json', models.TextField(null=True)),
                ('pdf_id', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backend_org.Employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_org.Org')),
            ],
            options={
                'db_table': 'tseg_request',
            },
        ),
    ]
