# Generated by Django 3.0.7 on 2021-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_tsegrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsegrequest',
            name='point_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tsegrequest',
            name='point_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tsegrequest',
            name='point_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tsegrequest',
            name='point_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
