# Generated by Django 3.0.7 on 2021-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20210321_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsegrequest',
            name='aimag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tsegrequest',
            name='sum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
