# Generated by Django 3.0.6 on 2020-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='СуурьДавхарга',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=500)),
                ('thumbnail_1x', models.ImageField(upload_to='суурь_давхарга/thumbnail_1x/')),
                ('thumbnail_2x', models.ImageField(upload_to='суурь_давхарга/thumbnail_2x/')),
            ],
        ),
    ]
