# Generated by Django 3.0.6 on 2020-06-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_суурь_давхарга', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='суурьдавхарга',
            table='суурь_давхарга',
        ),
    ]
