# Generated by Django 3.0.6 on 2020-06-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_суурь_давхарга', '0004_auto_20200615_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СуурьДавхарга',
            new_name='BaseLayer',
        ),
    ]
