# Generated by Django 3.0.6 on 2020-06-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_суурь_давхарга', '0005_auto_20200620_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baselayer',
            table='base_layer',
        ),
    ]
