# Generated by Django 3.0.7 on 2020-06-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_суурь_давхарга', '0007_baselayer_tilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
